export const data = [
    {
    "id": 1,
    "Name": "Barley Wine",
    "img": "https://i.postimg.cc/qBGDm5GJ/barley-wine.jpg",
    "Description": "El Barley Wine, literalmente Vino de Cebada en inglés, es de las cervezas más potentes que se elaboran. Su graduación puede superar el 10% y su sabor es tan intenso que se suele servir en copa pequeña. El secreto de esta receta de cerveza está en la gran cantidad de malta que lleva (sobre todo malta base) y una dosis nada despreciable de lúpulos.",
    "Price": 2000,
    "Stock": 50,
    "Color":"Cobrizo",
    "Style":"Fuerte",
    "Category":"Britanica" ,
   
  },
  {
    "id": 2,
    "Name": "Bitter",
    "img": "https://i.postimg.cc/FssWwVPj/cerveza-bitter.jpg",
    "Description": "La cerveza bitter (que significa amargo en inglés) no tiene demasiadas sorpresas en lo que se refiere a sus ingredientes. Suelen usar una malta suave y mucho lúpulo. Esta receta se aprovecha de esta circunstancia para simplificar y mucho las cosas. Utiliza exclusivamente extracto de malta clara (light) lo que nos ahorra directamente el macerado. Las maltas son una mezcla anglo-americana que este mundo global nos permite hacer sin problemas. Se obtiene una cerveza relativamente poco alcohólica, clara de color y con poca retención de espuma. Es decir, una genuina cerveza de Pub inglés.",
    "Price": 2000,
    "Stock": 50,
    "Style":"Liviana",
    "Color":"Clara",
    "Category":"Britanica",
    
  },
  {
    "id": 3,
    "Name": "Brown Ale",
    "img": "https://i.postimg.cc/1tG71ChK/cerveza-brown-ale.jpg",
    "Description": "Las Brown Ales son cervezas típicas inglesas y por herencia, americanas, en las que predomina el sabor a malta con un punto de amargor gracias a las maltas oscuras que forman parte de su receta. El color marrón es también consecuencia inevitable de esta combinación de maltas. En este caso te proponemos una receta de cerveza Brown Ale todo grano que es relativamente suave y fácil de beber.",
    "Price": 1000,
    "Stock":50,
    "Style":"Suave",
    "Color":"Marron",
    "Category": "Britanica",
    
  },
  {
    "id": 4,
    "Name": "India Pale Ale",
    "img": "https://i.postimg.cc/nrnRF4nf/english-pale-ale.jpg",
    "Description": "Esta es una receta “todo grano” con una buena combinación y juego de lúpulos como corresponde a las cervezas de tipo IPA. El resultado es una cerveza con una graduación superior a 5% y un sabor intenso.",
    "Price": 1000,
    "Stock":50,
    "Style":"Fuerte",
    "Color":"Cobrizo",
    "Category": "Britanica",
   
  },
  {
    "id": 5,
    "Name": "Pale Ale",
    "img": "https://i.postimg.cc/WzS9hd4F/cerveza-pale-ale.jpg",
    "Description": "Las cervezas de la categoría Pale Ale se elaboran a partir de malta pálida con el añadido, en algunas recetas de de cantidades pequeñas de malta cristal o tostada para darle un poco de color. En esta categoría entran recetas tan conocidas como para IPA (India Pale Ale), las American Pale Ale o las más genuinas Ales británicas. Se utilizan normalmente lúpulos ingleses tales como Kent Goldins o Fuggles, que le dan su amargor tan característico. Esta receta que nos ocupa hoy parte de una base de extracto de malta pálida que se combina con pequeñas cantidades de malta molida más oscura para darle el tono y sabor perfecto. La gravedad inicial debe estar alrededor de 1.056 para acabar cerca de 1.010 lo que implica una graduación alcohólica relativamente alta, cercana al 6%.",
    "Price": 1000,
    "Stock":50,
    "Style":"Liviana",
    "Color":"Dorada",
    "Category": "Britanica",
    
  },
  {
    "id": 6,
    "Name": "Scottish Ale",
    "img": "https://i.postimg.cc/mDfpqxqD/cerveza-grano-scottish-escocesa-ale.jpg",
    "Description": "Las cervezas Ale escocesas o Scottish Ales por su nombre en inglés son a la vez potentes y sobrias, muy bebibles pero sólo para paladares ya entrenados en el disfrute de cervezas Ale auténticas. Esta receta todo grano es una reciente ganadora de concurso nacional en USA y desde luego vale la pena probarla.",
    "Price": 1000,
    "Stock":50,
    "Style":"Amarga",
    "Color":"Roja",
    "Category": "Escocesa",
    
  },
  {
    "id": 7,
    "Name": "Stout",
    "img": "https://i.postimg.cc/dVhHnR64/receta-cerveza-negra-stout-americana-imperial.jpg",
    "Description": "Las cervezas negras o Stouts genuinamente irlandesas son muy secas y con un claro predominio de la malta con apenas un toque de lúpulo para aportar amargor. Esta receta que nos propone Weyermann requiere un macerado estable a una única temperatura para garantizar un resultado muy seco.",
    "Price": 1000,
    "Stock":50,
    "Style":"Dulce",
    "Color":"Oscuro",
    "Category": "Irlandes",
    
  },
  {
    "id": 8,
    "Name": "Irish Red Ale",
    "img": "https://i.postimg.cc/xTTFNVzr/irish-red-ale.gif",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Style":"Suave",
    "Color":"Roja",
    "Category": "Irlandes",
    
  },
  {
    "id": 9,
    "Name": "Gold Ale",
    "img": "https://i.postimg.cc/PqZ6ntBD/KITS-DORADA.png",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Style":"Suave",
    "Color":"Dorada",
    "Category": "Irlandes",
    
  },
  {
    "id": 10,
    "Name": "Bière d'abbaye",
    "img": "https://i.postimg.cc/dtsVx6hR/Biere-Abbaye-Belge.jpg",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Belga",
    
  },
  {
    "id": 11,
    "Name": "Bière aux fruits",
    "img": "https://i.postimg.cc/ZRSwTGSM/framboise.webp",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Belga",
    
  },
  {
    "id": 12,
    "Name": "Bière blanche",
    "img": "https://i.postimg.cc/mZS5rghN/Bi-re-blanche.jpg",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Belga",
    
  },
  {
    "id": 13,
    "Name": "Bière blonde",
    "img": "https://i.postimg.cc/sgbnLB0y/biere-blonde.jpg",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Belga",
    
  },
  {
    "id": 14,
    "Name": "Bière double",
    "img": "https://i.postimg.cc/ZK7srs8W/Verre-Doublel.webp",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Belga",
    
  },
  {
    "id": 15,
    "Name": "Bière blonde forte",
    "img": "https://i.postimg.cc/1XMC7JbY/Bi-re-blonde-forte.jpg",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Belga",
    
  },
  {
    "id": 16,
    "Name": "Altbier",
    "img": "https://i.postimg.cc/kG7YykYb/altbier.jpg",
    "Description": "La cerveza Altbier, también conocida como Alt, es una cerveza ámbar Alemana, de intenso y rico sabor. En este caso te proponemos una receta que combina grano (malta Munich) y extracto húmedo y seco.",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Aleman",
    
  },
  {
    "id": 17,
    "Name": "Kellerweizen",
    "img": "https://i.postimg.cc/MKgQ8XRt/keller-Weizen.jpg",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Aleman",
    
  },
  {
    "id": 18,
    "Name": "Kölsch ",
    "img": "https://i.postimg.cc/PqtkRz6D/kolch.jpg",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Aleman",
    
  },
  {
    "id": 19,
    "Name": "Rauchbier",
    "img": "https://i.postimg.cc/bv3jcDMB/Rauchbier.jpg",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Aleman",
    
  },
  {
    "id": 20,
    "Name": "Steinbier",
    "img": "https://i.postimg.cc/tTJGXRGC/Weizenbier.jpg",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Aleman",
    
  },
  {
    "id": 21,
    "Name": "Weizenbier",
    "img": "https://i.ibb.co/0DwNRHg/razer-cynosa-v2-500x500.png",
    "Description": "bla bla",
    "Price": 1000,
    "Stock":50,
    "Color":"Marron",
    "Category": "Aleman",
    
  },
  
]
